all:
  hosts:
    control_plane:
      ansible_host: 10.11.1.10
      new_hostname: master
      kube_version: "1.31.1"
      pod_network_cidr: "192.168.0.0/16"

    worker:
      ansible_host: 10.11.1.11
      new_hostname: worker
      kube_version: "1.31.1"

  vars:
    ansible_user: kubilay
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
