# setup_docker_kubernetes.yaml
---
- name: Install prerequisite packages
  hosts: all
  become: true
  tasks:
    - name: Update APT package index
      apt:
        update_cache: true

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - software-properties-common
        state: present

    - name: Disable swap
      command: sudo swapoff -a
      changed_when: false

    - name: Comment out swap in /etc/fstab
      command: sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      changed_when: false

    - name: Load overlay kernel module
      command: sudo modprobe overlay
      changed_when: false

    - name: Load br_netfilter kernel module
      command: sudo modprobe br_netfilter
      changed_when: false

    - name: Configure sysctl for Kubernetes
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: "0644"

    - name: Apply sysctl settings
      command: sudo sysctl --system
      changed_when: false
