---
- name: Initialize Kubernetes cluster
  hosts: control_plane
  become: true
  tasks:
    - name: Initialize Kubernetes cluster
      command: "kubeadm init --pod-network-cidr={{ pod_network_cidr }}"
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory for the admin user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy admin.conf to user's home directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
