---
- name: Install and configure containerd
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install containerd
      apt:
        name:
          - containerd.io
        state: latest

    - name: Create containerd configuration directory
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd configuration
      command: containerd config default
      register: containerd_config
      args:
        creates: /etc/containerd/config.toml

    - name: Write containerd configuration to file
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Restart and enable containerd service
      systemd:
        name: containerd
        state: restarted
        enabled: true

    - name: Verify containerd installation
      command: containerd --version
      register: containerd_version

    - name: Display containerd version
      debug:
        var: containerd_version.stdout
