---
- name: Install Calico CNI
  hosts: control_plane
  become: true
  tasks:
    - name: Download Calico manifest
      get_url:
        url: "https://docs.projectcalico.org/manifests/calico.yaml"
        dest: /tmp/calico.yaml

    - name: Apply Calico CNI plugin
      command: kubectl apply -f /tmp/calico.yaml
