---
- name: Install and configure Kubernetes prerequisites
  hosts: all
  become: true
  tasks:
    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet={{ kube_version }}
          - kubeadm={{ kube_version }}
          - kubectl={{ kube_version }}
        state: present
        update_cache: yes

    - name: Ensure kubelet is enabled and started
      systemd:
        name: kubelet
        state: started
        enabled: true
